service:
  name: hello-job
  type: job
  env: dev
  team: demo

image:
  repo: busybox
  tag: "1.36"

resources:
  profile: job-small

job:
  command: ["sh", "-c", "echo hello from job && sleep 2"]
  backoffLimit: 1
  ttlSecondsAfterFinished: 120
